# Generated by Django 4.1.2 on 2022-10-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Наименование')),
                ('image', models.ImageField(default='no_image.jpg', upload_to='goods', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Piercing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Татуировка', max_length=50, verbose_name='Наименование')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('duration', models.IntegerField(default=30, verbose_name='Длительность процедуры')),
                ('is_busy_pier', models.BooleanField(default=False, verbose_name='Отметьте, если занято.')),
            ],
            options={
                'verbose_name': 'Запись ',
                'verbose_name_plural': 'Записи. Тату. ',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('procedure', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи. Пирсинг. ',
            },
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Татуировка', max_length=50, verbose_name='Наименование')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('duration', models.IntegerField(default=15, verbose_name='Длительность процедуры')),
                ('is_busy_tatt', models.BooleanField(default=False, verbose_name='Отметьте, если занято.')),
            ],
            options={
                'verbose_name': 'Запись ',
                'verbose_name_plural': 'Записи. Тату. ',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=40, verbose_name='Отчество')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
