# Generated by Django 4.1.2 on 2022-10-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AlterModelOptions(
            name='piercing',
            options={'verbose_name': 'Запись ', 'verbose_name_plural': 'Записи. Пирсинг. '},
        ),
    ]
